name: savant-env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - scipy
  - torch
  - faiss-cpu=1.11.0
  - gitpython
  - huggingface_hub
  - flake8
  - pytest
  - pip
  - pip:
      - accelerate
      - transformers>=4.44.0
